// board_view.cpp
//
// Draws a checkered 8x8 board, then a test row of every piece sprite we
// have. This isn't real chess position layout yet, it's just "does
// every texture actually load and draw."
#include <3ds.h>
#include <citro2d.h>
#include <cstdio>
#include "board_view.h"
#include "spritesheet.h" // generated by tex3ds at build time -- defines
                          // spritesheet_white_king_idx, spritesheet_white_queen_idx, etc.
                          // (one constant per line in gfx/spritesheet.t3s, in that order)

// The 3DS bottom screen is 320x240. Giving each square 30x30 pixels
// makes a 240x240 board, leaving an even margin on both sides.
static constexpr int SQUARE_SIZE  = 30;
static constexpr int BOARD_PIXELS = SQUARE_SIZE * 8;              // 240
static constexpr int BOARD_X      = (320 - BOARD_PIXELS) / 2;      // centered horizontally
static constexpr int BOARD_Y      = (240 - BOARD_PIXELS) / 2;      // centered vertically

static C3D_RenderTarget* bottomTarget = nullptr;
static C2D_SpriteSheet piecesSheet = nullptr;

// Order matches gfx/spritesheet.t3s exactly, for our test-row layout below.
static const int pieceIndices[] = {
    spritesheet_white_king_idx,
    spritesheet_white_queen_idx,
    spritesheet_white_rook_idx,
    spritesheet_white_bishop_idx,
    spritesheet_white_knight_idx,
    spritesheet_white_pawn_idx,
    spritesheet_black_king_idx,
    spritesheet_black_queen_idx,
    spritesheet_black_rook_idx,
    spritesheet_black_bishop_idx,
    spritesheet_black_knight_idx,
    spritesheet_black_pawn_idx,
};
static constexpr int NUM_PIECES = sizeof(pieceIndices) / sizeof(pieceIndices[0]);

void board_view_init()
{
    // Mount the embedded RomFS so "romfs:/..." paths work. If this
    // fails, the texture load below will fail too, so we print clearly
    // rather than silently drawing nothing.
    Result romfsResult = romfsInit();
    if (romfsResult != 0)
        printf("[board_view] romfsInit FAILED: 0x%08lX\n", romfsResult);
    else
        printf("[board_view] romfsInit ok\n");

    C3D_Init(C3D_DEFAULT_CMDBUF_SIZE);
    C2D_Init(C2D_DEFAULT_MAX_OBJECTS);
    C2D_Prepare();

    bottomTarget = C2D_CreateScreenTarget(GFX_BOTTOM, GFX_LEFT);

    piecesSheet = C2D_SpriteSheetLoad("romfs:/gfx/spritesheet.t3x");
    if (!piecesSheet)
        printf("[board_view] FAILED to load spritesheet.t3x\n");
    else
        printf("[board_view] spritesheet loaded ok\n");
}

void board_view_draw()
{
    // Classic green/cream chess-board colors.
    const u32 lightSquare = C2D_Color32(0xEE, 0xEE, 0xD2, 0xFF);
    const u32 darkSquare  = C2D_Color32(0x76, 0x96, 0x56, 0xFF);
    const u32 background  = C2D_Color32(0x20, 0x20, 0x20, 0xFF);

    C3D_FrameBegin(C3D_FRAME_SYNCDRAW);
    C2D_TargetClear(bottomTarget, background);
    C2D_SceneBegin(bottomTarget);

    for (int row = 0; row < 8; row++)
    {
        for (int col = 0; col < 8; col++)
        {
            bool isLight = ((row + col) % 2 == 0);
            u32 color = isLight ? lightSquare : darkSquare;

            float x = static_cast<float>(BOARD_X + col * SQUARE_SIZE);
            float y = static_cast<float>(BOARD_Y + row * SQUARE_SIZE);

            C2D_DrawRectSolid(x, y, 0.0f, SQUARE_SIZE, SQUARE_SIZE, color);
        }
    }

    // Test row: draw every piece across the top two ranks (6 per row,
    // since we now have 12), just to confirm each texture shows up.
    // Not a real starting position -- purely a "does it render" check.
    if (piecesSheet)
    {
        for (int i = 0; i < NUM_PIECES; i++)
        {
            int col = i % 6;
            int row = (i < 6) ? 0 : 1;

            float x = static_cast<float>(BOARD_X + col * SQUARE_SIZE);
            float y = static_cast<float>(BOARD_Y + row * SQUARE_SIZE);

            C2D_Image img = C2D_SpriteSheetGetImage(piecesSheet, pieceIndices[i]);
            C2D_DrawImageAt(img, x, y, 0.5f);
        }
    }

    C3D_FrameEnd(0);
}

void board_view_exit()
{
    if (piecesSheet)
        C2D_SpriteSheetFree(piecesSheet);

    C2D_Fini();
    C3D_Fini();
    romfsExit();
}
